owner: idammi
repo: status

assignees:
  -  idammi

sites:
  - name: SocialGenius.net
    url: https://app.socialgenius.net
    icon: https://app.socialgenius.net/favicon.ico
    maxResponseTime: 30000
  - name: SocialGenius.net Store
    url: https://store.socialgenius.net
    icon: https://store.socialgenius.net/wp-content/uploads/2021/02/cropped-favicon-192x192.png
    maxResponseTime: 30000
  - name: TikTok API
    url: $TIKTOK_API_ENDPOINT
    headers:
      - "Authorization: Bearer $TIKTOK_API_TOKEN"
    icon: https://app.socialgenius.net/favicon.ico?version=dark
    maxResponseTime: 30000

status-website:
  cname: status.socialgenius.net
  logoUrl: https://app.socialgenius.net/favicon.ico
  favicon: https://app.socialgenius.net/favicon.ico
  name: SocialGenius Status
  introTitle: "**SocialGenius** uptime monitor and status page"
  introMessage: This status page uses **real-time** data from [SocialGenius](https://socialgenius.net) servers.
      
commitMessages:
  commitAuthorName: "SocialGenius Bot"
  commitAuthorEmail: "dami@socialgenius.net"
